### ISSUE TITLE
Wrong getFileList() from this file

### ISSUE THREAD

**Issue by Vance-ng-vn** [YuJianrong/node-unrar.js#330]
```
UnrarError: File read error
    at ExtractorData.getFailException (/home/mx-vankaiser/Projects/test/node_modules/node-unrar-js/dist/js/Extractor.js:187:16)
    at ExtractorData.openArc (/home/mx-vankaiser/Projects/test/node_modules/node-unrar-js/dist/js/Extractor.js:108:24)
    at ExtractorData.getFileList (/home/mx-vankaiser/Projects/test/node_modules/node-unrar-js/dist/js/Extractor.js:54:32)
    at main (/home/mx-vankaiser/Projects/test/nodeunrarjs.js:9:26) {
  reason: 'ERAR_EREAD',
  file: undefined
}
```

[the-rocky-horror-picture-show_spanish-138854.rar.zip](https://github.com/YuJianrong/node-unrar.js/files/13518480/the-rocky-horror-picture-show_spanish-138854.rar.zip)

**Comment by YuJianrong** [comment]
The `the-rocky-horror-picture-show_spanish-138854.rar` is a zip file, not a RAR file.

![image](https://github.com/YuJianrong/node-unrar.js/assets/176076/a147cbca-382e-4598-81c4-a7c10a810ec1)
