### ISSUE TITLE
const extracted = extractor.extract() 加一个选项吧 手动指定unrar的output目录...

### ISSUE THREAD

**Issue by gowy222** [YuJianrong/node-unrar.js#40]
特定环境云函数只有一个可读写/tmp 目录... 只能手动指定解压fromfile的时候 解压到 指定/tmp/自定义新目录,不然读写会报错

Error: ENOENT: no such file or directory, mkdir 'testfile1.htm'

```
    at Object.mkdirSync (fs.js:1013:3)

    at ExtractorFile.create (/var/user/node_modules/node-unrar-js/dist/js/ExtractorFile.js:54:16)

    at _jsCreate (/var/user/node_modules/node-unrar-js/dist/js/unrar.js:9:57667)

    at <anonymous>:wasm-function[278]:0x1bce6

    at <anonymous>:wasm-function[182]:0x12974

    at <anonymous>:wasm-function[417]:0x2cda4

    at invoke_iiii (/var/user/node_modules/node-unrar-js/dist/js/unrar.js:9:63577)

    at <anonymous>:wasm-function[420]:0x2e1f2

    at invoke_iiiii (/var/user/node_modules/node-unrar-js/dist/js/unrar.js:9:63411)

    at <anonymous>:wasm-function[216]:0x17021
```

**Comment by YuJianrong** [comment]
这个选项已经有了，叫`targetPath`：https://github.com/YuJianrong/node-unrar.js#api-to-create-the-extractor
在test文件中有例子：
https://github.com/YuJianrong/node-unrar.js/blob/master/src/test/ExtractorFile.spec.ts#L120
